name: Admin Nomination
description: Submit this issue to nominate yourself or another person as an admin
title: "[NOMINATION]"
body:
  - type: markdown
    id: overview
    attributes:
      value: |
        Please submit this form to nominate yourself or someone else as an admin. This can be as short or
        as long as you like, and **every field is optional** but more detail helps us understand what kinds
        of tasks you would help with as an admin.

        You may wish to refer to our [list of tasks admins do](https://github.com/TheSpatialCommunity/documents/blob/base/ADMIN_JOBS.md) to better understand roles that the nominee would fill.

        Currently, admins are selected by the existing admin team after comment from the broader community.
        A nomination here is the first step toward getting comments.
  - type: checkboxes
    id: read-the-details
    attributes:
      label: I have looked at the list of tasks admins do.
      description: Make sure you understand the [role of the admins](https://github.com/TheSpatialCommunity/documents/blob/base/ADMIN_JOBS.md) in this community before nominating. 
      options:
        - label: The person I am nominating would be able to support one or more of the items in the listed admin tasks.
          required: true
  - type: input
    id: nominee
    attributes:
      label: The Spatial Community User You Are Nominating
      description: What is the username or display name of the user you are nominating in The Spatial Community? If the display name is ambiguous, make sure to use the username (this one is not optional)
      placeholder: 
    validations:
      required: true
  - type: dropdown
    id: nominating-for
    attributes:
      label: Nominating for
      description: Are you nominating yourself, or someone else?
      options:
        - Self
        - Someone else
      default: 0
    validations:
      required: true
  - type: input
    id: nominator
    attributes:
      label: Your Spatial Community Username
      description: If you are nominating someone else, then include your own username here. Optional otherwise.
      placeholder: 
    validations:
      required: false
  - type: textarea
    id: why-a-fit
    attributes:
      label: Why are you nominating this person?
      description: What would make this person (or youself) a good admin in the community, and what roles could they fill and support?
    validations:
      required: false
  - type: markdown
    id: next-section
    attributes:
      value: |
        The following questions are best filled out by self-nominees. If you are nominating someone else, you can skip
        over these questions and the nominee can fill it out when they submit their own nomination.
  - type: textarea
    id: currently-like
    attributes:
      label: What do you currently like about the community?
      description: What are the aspects of the community you currently like and that you would like to continue or preserve?
    validations:
      required: false
  - type: textarea
    id: what-change
    attributes:
      label: What would you consider changing about the community, if anything?
      description: 
    validations:
      required: false
  - type: textarea
    id: support
    attributes:
      label: Which of the [listed admin tasks](https://github.com/TheSpatialCommunity/documents/blob/base/ADMIN_JOBS.md) would you be most able to support?
      description: Admins don't need to do all the tasks, but we need to build a team that covers all the roles well.
    validations:
      required: false
  - type: textarea
    id: special-skills
    attributes:
      label: Any other special skills or relevant experience?
      description: List any other skills here that might be relevent (such as creating Python Slack bots, maintaining websites, etc), or experience (such as community moderation_)
    validations:
      required: false
  - type: markdown
    id: thanks
    attributes:
      value: |
        Thank you! We're looking to broaden and diversify our admin team. We're looking forward to reviewing your nomination.
